### ISSUE TITLE
API 400 status after submitting ContactForm

### ISSUE THREAD

**Issue by jzenzinger** [Seybel/vue-emailjs-demo#1] opened 2022-02-10 22:29 UTC
After I cloned project, install it, this error shows after adding information to form and submitting.
<img width="1205" alt="Screenshot 2022-02-10 at 23 28 09" src="https://user-images.githubusercontent.com/56548420/153507324-683fd9f1-0ebe-4f55-a61c-5c0655e605b2.png">

**Comment by Seybel** [comment] 2022-02-13 09:57
Make sure you are sending the right payload as that might be the cause of the issue.

**Comment by Seybel** [comment] 2022-02-13 15:47
> After I cloned project, install it, this error shows after adding information to form and submitting. <img alt="Screenshot 2022-02-10 at 23 28 09" width="1205" src="https://user-images.githubusercontent.com/56548420/153507324-683fd9f1-0ebe-4f55-a61c-5c0655e605b2.png">

 I just checked again and all seems fine. 
    1. Make sure you are sending the right payload
    2. Make sure your email service is connected.
  I will be closing the issue now. If you need further help, do not hesitate to reach out.
  Cheers🥂

**Closed as completed by Seybel** 2022-02-13 15:47 UTC
